IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].Movie') AND type in (N'U'))
	DROP TABLE Movie

CREATE TABLE Movie (
	ID int IDENTITY PRIMARY KEY,
	YourRating int,
	DateRated nchar(10),
	Title nvarchar(100),
	[URL] nvarchar(100),
	TitleType nvarchar(20),
	IMDbRating float,
	Runtimemins int,
	[Year] int,
	Genres nvarchar(60),
	ReleaseDate nchar(10),
	Directors nvarchar(60),
	[Cast] nvarchar(200)
)

INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-07-04','Druk','https://www.imdb.com/title/tt10288566/','movie',7.7,117,2020,'Comedy, Drama','2020-09-12','Thomas Vinterberg', 'Mads Mikkelsen, Thomas Bo Larsen, Magnus Millang, Lars Ranthe');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-08-01','The Silence of the Lambs','https://www.imdb.com/title/tt0102926/','movie',8.6,118,1991,'Crime, Drama, Thriller','1991-01-30','Jonathan Demme', 'Jodie Foster, Anthony Hopkins');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2022-02-05','Reservoir Dogs','https://www.imdb.com/title/tt0105236/','movie',8.3,99,1992,'Crime, Drama, Thriller','1992-01-21','Quentin Tarantino', 'Harvey Keitel, Tim Roth, Steve Buscemi');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-12-29','Schindler''s List','https://www.imdb.com/title/tt0108052/','movie',9,195,1993,'Biography, Drama, History','1993-11-30','Steven Spielberg', 'Liam Neeson, Ralph Fiennes, Ben Kingsley');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2022-02-12','The Chestnut Man','https://www.imdb.com/title/tt10834220/','tvSeries',7.7,50,2021,'Crime, Drama, Mystery, Thriller','2021-09-29','', 'Danica Curcic, David Dencik, Mikkel Boe Følsgaard, Iben Dorner, Lars Ranthe');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2021-12-31','Spider-Man: No Way Home','https://www.imdb.com/title/tt10872600/','movie',8.7,148,2021,'Action, Adventure, Fantasy, Sci-Fi','2021-12-13','Jon Watts', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-07-18','Forrest Gump','https://www.imdb.com/title/tt0109830/','movie',8.8,142,1994,'Drama, Romance','1994-06-23','Robert Zemeckis', 'Tom Hanks');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-12-11','Léon','https://www.imdb.com/title/tt0110413/','movie',8.6,110,1994,'Action, Crime, Drama, Thriller','1994-09-14','Luc Besson', 'Jean Reno, Gary Oldman, Natalie Portman');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-30','Pulp Fiction','https://www.imdb.com/title/tt0110912/','movie',8.9,154,1994,'Crime, Drama','1994-05-21','Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis, Tim Roth, Harvey Keitel');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-02','The Shawshank Redemption','https://www.imdb.com/title/tt0111161/','movie',9.3,142,1994,'Drama','1994-09-10','Frank Darabont', 'Tim Robbins, Morgan Freeman');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-12','Shutter Island','https://www.imdb.com/title/tt1130884/','movie',8.2,138,2010,'Mystery, Thriller','2010-02-13','Martin Scorsese', 'Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-08-29','Se7en','https://www.imdb.com/title/tt0114369/','movie',8.6,127,1995,'Crime, Drama, Mystery, Thriller','1995-09-15','David Fincher', 'Morgan Freeman, Brad Pitt, Kevin Spacey');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-12','Dune: Part One','https://www.imdb.com/title/tt1160419/','movie',8.1,155,2021,'Action, Adventure, Drama, Sci-Fi','2021-09-03','Denis Villeneuve', 'Timothée Chalamet, Zendaya, Oscar Isaac, Jason Momoa, Stellan Skarsgård');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2022-01-20','Fargo','https://www.imdb.com/title/tt0116282/','movie',8.1,98,1996,'Crime, Thriller','1996-03-08','Ethan Coen, Joel Coen', 'William H. Macy, Frances McDormand, Steve Buscemi, Peter Stormare');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-11-21','Jerry Maguire','https://www.imdb.com/title/tt0116695/','movie',7.3,139,1996,'Comedy, Drama, Romance, Sport','1996-12-06','Cameron Crowe', 'Tom Cruise, Renée Zellweger');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-29','Trainspotting','https://www.imdb.com/title/tt0117951/','movie',8.2,93,1996,'Drama','1996-02-23','Danny Boyle', 'Ewan McGregor, Ewen Bremner, Jonny Lee Miller, Kevin McKidd');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-29','The Big Lebowski','https://www.imdb.com/title/tt0118715/','movie',8.1,117,1998,'Comedy, Crime','1998-01-18','Ethan Coen, Joel Coen', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-02','Good Will Hunting','https://www.imdb.com/title/tt0119217/','movie',8.3,126,1997,'Drama, Romance','1997-12-02','Gus Van Sant', 'Robin Williams, Matt Damon, Ben Affleck, Stellan Skarsgård');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-12','The Truman Show','https://www.imdb.com/title/tt0120382/','movie',8.2,103,1998,'Comedy, Drama','1998-06-01','Peter Weir', 'Jim Carrey, Ed Harris, Laura Linney');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-07-29','The Green Mile','https://www.imdb.com/title/tt0120689/','movie',8.6,189,1999,'Crime, Drama, Fantasy, Mystery','1999-12-06','Frank Darabont', 'Tom Hanks, Michael Clarke Duncan, David Morse, Sam Rockwell');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-11-20','The World''s End','https://www.imdb.com/title/tt1213663/','movie',7,109,2013,'Comedy, Sci-Fi','2013-07-10','Edgar Wright', 'Simon Pegg, Nick Frost, Martin Freeman');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2021-11-20','Bellflower','https://www.imdb.com/title/tt1242599/','movie',6.3,103,2011,'Action, Drama, Romance','2011-01-21','Evan Glodell', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-08-08','The Matrix','https://www.imdb.com/title/tt0133093/','movie',8.7,136,1999,'Action, Sci-Fi','1999-03-24','Lilly Wachowski, Lana Wachowski', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-30','Fight Club','https://www.imdb.com/title/tt0137523/','movie',8.8,139,1999,'Drama','1999-09-10','David Fincher', 'Brad Pitt, Edward Norton');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-07-30','Inception','https://www.imdb.com/title/tt1375666/','movie',8.8,148,2010,'Action, Adventure, Sci-Fi, Thriller','2010-07-08','Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Ken Watanabe, Tom Hardy');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-05','American Psycho','https://www.imdb.com/title/tt0144084/','movie',7.6,102,2000,'Crime, Drama, Horror','2000-01-21','Mary Harron', 'Christian Bale, Reese Witherspoon, Jared Leto, Willem Dafoe');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-08-11','Intouchables','https://www.imdb.com/title/tt1675434/','movie',8.5,112,2011,'Biography, Comedy, Drama','2011-09-23','Olivier Nakache, Éric Toledano', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2022-01-10','Django Unchained','https://www.imdb.com/title/tt1853728/','movie',8.5,165,2012,'Drama, Western','2012-12-11','Quentin Tarantino', 'Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington, Samuel L. Jackson');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-12-22','Band of Brothers','https://www.imdb.com/title/tt0185906/','tvMiniSeries',9.4,594,2001,'Drama, History, War','2001-09-09','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-02','Ford v Ferrari','https://www.imdb.com/title/tt1950186/','movie',8.1,152,2019,'Action, Biography, Drama, Sport','2019-08-30','James Mangold', 'Matt Damon, Christian Bale, Jon Bernthal');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-12-15','Snatch','https://www.imdb.com/title/tt0208092/','movie',8.3,104,2000,'Comedy, Crime','2000-08-23','Guy Ritchie', 'Jason Statham, Brad Pitt, Stephen Graham');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-07-02','Black Mirror','https://www.imdb.com/title/tt2085059/','tvSeries',8.8,60,2011,'Drama, Mystery, Sci-Fi, Thriller','2011-12-04','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-08-30','Jagten','https://www.imdb.com/title/tt2106476/','movie',8.3,115,2012,'Drama','2012-05-20','Thomas Vinterberg', 'Mads Mikkelsen, Thomas Bo Larsen, Lars Ranthe');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-02','The Grand Budapest Hotel','https://www.imdb.com/title/tt2278388/','movie',8.1,99,2014,'Adventure, Comedy, Crime','2014-02-06','Wes Anderson', 'Ralph Fiennes, Adrien Brody, Willem Dafoe, Jeff Goldblum, Edward Norton, Saoirse Ronan, Harvey Keitel, Tom Wilkinson');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-02','Whiplash','https://www.imdb.com/title/tt2582802/','movie',8.5,106,2014,'Drama, Music','2014-01-16','Damien Chazelle', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-09-05','Catch Me If You Can','https://www.imdb.com/title/tt0264464/','movie',8.1,141,2002,'Biography, Crime, Drama','2002-12-16','Steven Spielberg', 'Leonardo DiCaprio, Tom Hanks, Christopher Walken');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2022-03-04','Kill Bill: Vol. 1','https://www.imdb.com/title/tt0266697/','movie',8.2,111,2003,'Action, Crime, Drama, Thriller','2003-09-29','Quentin Tarantino', 'Uma Thurman, David Carradine, Daryl Hannah, Michael Madsen, Lucy Liu, Julie Dreyfus');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-10-07','A Beautiful Mind','https://www.imdb.com/title/tt0268978/','movie',8.2,135,2001,'Biography, Drama','2001-12-13','Ron Howard', 'Russell Crowe, Ed Harris, Jennifer Connelly, Christopher Plummer');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-11-20','Moszkva tér','https://www.imdb.com/title/tt0273840/','movie',7.8,88,2001,'Comedy, Drama, Romance','2001-02-01','Ferenc Török', 'Eszter Balla');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-04','Eternal Sunshine of the Spotless Mind','https://www.imdb.com/title/tt0338013/','movie',8.3,108,2004,'Drama, Romance, Sci-Fi','2004-03-09','Michel Gondry', 'Jim Carrey, Kate Winslet, Tom Wilkinson, Elijah Wood, Mark Ruffalo, Kirsten Dunst');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2022-01-17','Salinui chueok','https://www.imdb.com/title/tt0353969/','movie',8.1,131,2003,'Crime, Drama, Mystery, Thriller','2003-05-02','Bong Joon Ho', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-12-12','Inglourious Basterds','https://www.imdb.com/title/tt0361748/','movie',8.3,153,2009,'Adventure, Drama, War','2009-05-20','Quentin Tarantino', 'Brad Pitt, Christoph Waltz, Diane Kruger, Mélanie Laurent, Julie Dreyfus');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-11-20','Shaun of the Dead','https://www.imdb.com/title/tt0365748/','movie',7.9,99,2004,'Comedy, Horror','2004-03-29','Edgar Wright', 'Simon Pegg, Nick Frost, Kate Ashfield');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-08-08','Kontroll','https://www.imdb.com/title/tt0373981/','movie',7.6,111,2003,'Comedy, Crime, Drama, Romance, Thriller','2003-11-20','Nimród Antal', 'Sándor Csányi, Eszter Balla, Zoltán Mucsi, Csaba Pindroch');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2022-02-26','Synecdoche, New York','https://www.imdb.com/title/tt0383028/','movie',7.5,124,2008,'Drama','2008-05-23','Charlie Kaufman', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-07-02','The Office','https://www.imdb.com/title/tt0386676/','tvSeries',9,22,2005,'Comedy','2005-03-24','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-08-03','Baby Driver','https://www.imdb.com/title/tt3890160/','movie',7.6,113,2017,'Action, Crime, Drama, Music, Thriller','2017-03-11','Edgar Wright', 'Ansel Elgort, Kevin Spacey, Jamie Foxx');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2022-01-12','Das Leben der Anderen','https://www.imdb.com/title/tt0405094/','movie',8.4,137,2006,'Drama, Mystery, Thriller','2006-03-15','Florian Henckel von Donnersmarck', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-08-21','The Departed','https://www.imdb.com/title/tt0407887/','movie',8.5,151,2006,'Crime, Drama, Thriller','2006-09-26','Martin Scorsese', 'Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-11-20','Hot Fuzz','https://www.imdb.com/title/tt0425112/','movie',7.8,121,2007,'Action, Comedy, Mystery, Thriller','2007-02-13','Edgar Wright', 'Simon Pegg, Nick Frost, Martin Freeman');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-11-20','Fantastic Mr. Fox','https://www.imdb.com/title/tt0432283/','movie',7.9,87,2009,'Animation, Adventure, Comedy, Crime, Drama, Family','2009-10-14','Wes Anderson', 'George Clooney, Meryl Streep, Willem Dafoe');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-07-02','Stranger Things','https://www.imdb.com/title/tt4574334/','tvSeries',8.7,51,2016,'Drama, Fantasy, Horror, Mystery, Sci-Fi, Thriller','2016-07-11','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-11-20','How I Met Your Mother','https://www.imdb.com/title/tt0460649/','tvSeries',8.4,22,2005,'Comedy, Romance','2005-09-19','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2021-12-17','The Death of Stalin','https://www.imdb.com/title/tt4686844/','movie',7.2,107,2017,'Comedy, Drama, History','2017-09-08','Armando Iannucci', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-16','Rear Window','https://www.imdb.com/title/tt0047396/','movie',8.5,112,1954,'Mystery, Thriller','1954-08-01','Alfred Hitchcock', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-04','12 Angry Men','https://www.imdb.com/title/tt0050083/','movie',9,96,1957,'Crime, Drama','1957-04-10','Sidney Lumet', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2022-01-08','Three Billboards Outside Ebbing, Missouri','https://www.imdb.com/title/tt5027774/','movie',8.1,115,2017,'Comedy, Crime, Drama','2017-09-04','Martin McDonagh', 'Frances McDormand, Woody Harrelson, Sam Rockwell, Peter Dinklage');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-07-02','Aranyélet','https://www.imdb.com/title/tt5099020/','tvSeries',8.8,60,2015,'Action, Crime, Drama, Thriller','2015-11-08','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-19','The Witcher','https://www.imdb.com/title/tt5180504/','tvSeries',8.3,60,2019,'Action, Adventure, Drama, Fantasy, Mystery','2019-12-20','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (4,'2021-12-29','Riverdale','https://www.imdb.com/title/tt5420376/','tvSeries',6.8,45,2017,'Crime, Drama, Mystery, Romance','2017-01-26','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-11-22','A tizedes meg a többiek','https://www.imdb.com/title/tt0059812/','movie',8.4,111,1965,'Comedy, War','1965-04-15','Márton Keleti', 'Tamás Major, Imre Sinkovits, Iván Darvas');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-08-13','The End of the F***ing World','https://www.imdb.com/title/tt6257970/','tvSeries',8.1,25,2017,'Adventure, Comedy, Crime, Drama, Romance, Thriller','2017-10-24','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-12-15','Isten hozta örnagy úr','https://www.imdb.com/title/tt0064498/','movie',8.1,95,1969,'Comedy, Drama','1969-11-29','Zoltán Fábri', 'Zoltán Latinovits, Imre Sinkovits');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-21','La casa de papel','https://www.imdb.com/title/tt6468322/','tvSeries',8.3,70,2017,'Action, Crime, Drama, Mystery, Thriller','2017-05-02','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2021-12-15','A tanú','https://www.imdb.com/title/tt0065067/','movie',8.7,105,1969,'Drama, Comedy','1969-05-23','Péter Bacsó', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-19','Gisaengchung','https://www.imdb.com/title/tt6751668/','movie',8.5,132,2019,'Comedy, Drama, Thriller','2019-05-21','Bong Joon Ho', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-03','The Godfather','https://www.imdb.com/title/tt0068646/','movie',9.2,175,1972,'Crime, Drama','1972-03-14','Francis Ford Coppola', 'Al Pacino, Diane Keaton, Marlon Brando, James Caan, Robert Duvall, John Cazale');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (2,'2022-01-17','Mamma Mia! Here We Go Again','https://www.imdb.com/title/tt6911608/','movie',6.6,114,2018,'Comedy, Musical, Romance','2018-07-11','Ol Parker', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-03','The Godfather: Part II','https://www.imdb.com/title/tt0071562/','movie',9,202,1974,'Crime, Drama','1974-12-12','Francis Ford Coppola', 'Al Pacino, Robert De Niro, Robert Duvall, Diane Keaton, John Cazale');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-30','One Flew Over the Cuckoo''s Nest','https://www.imdb.com/title/tt0073486/','movie',8.7,133,1975,'Drama','1975-11-19','Milos Forman', 'Jack Nicholson, Danny DeVito');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-07-02','Chernobyl','https://www.imdb.com/title/tt7366338/','tvMiniSeries',9.4,330,2019,'Drama, History, Thriller','2019-05-06','', 'Jessie Buckley, Jared Harris, Stellan Skarsgård');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-12-30','Taxi Driver','https://www.imdb.com/title/tt0075314/','movie',8.3,114,1976,'Crime, Drama','1976-02-08','Martin Scorsese', 'Robert De Niro, Jodie Foster, Cybill Shepherd');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-12-29','Az ötödik pecsét','https://www.imdb.com/title/tt0075467/','movie',8.6,111,1976,'Drama, War','1976-10-07','Zoltán Fábri', 'Zoltán Latinovits');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-11-07','Annie Hall','https://www.imdb.com/title/tt0075686/','movie',8,93,1977,'Comedy, Romance','1977-03-27','Woody Allen', 'Woody Allen, Diane Keaton');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2022-01-24','In Bruges','https://www.imdb.com/title/tt0780536/','movie',7.9,107,2008,'Comedy, Crime, Drama, Thriller','2008-01-17','Martin McDonagh', 'Colin Farrell, Brendan Gleeson');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-12-29','Life of Brian','https://www.imdb.com/title/tt0079470/','movie',8.1,94,1979,'Comedy','1979-08-17','Terry Jones', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2022-01-17','Mamma Mia!','https://www.imdb.com/title/tt0795421/','movie',6.5,108,2008,'Comedy, Musical, Romance','2008-06-30','Phyllida Lloyd', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-23','The Mandalorian','https://www.imdb.com/title/tt8111088/','tvSeries',8.8,40,2019,'Action, Adventure, Fantasy, Sci-Fi','2019-11-12','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-08-12','The Shining','https://www.imdb.com/title/tt0081505/','movie',8.4,146,1980,'Drama, Horror','1980-05-23','Stanley Kubrick', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-07-07','Formula 1: Drive to Survive','https://www.imdb.com/title/tt8289930/','tvSeries',8.7,40,2019,'Documentary, Sport','2019-03-08','', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2021-11-20','Midsommar','https://www.imdb.com/title/tt8772262/','movie',7.1,148,2019,'Drama, Horror, Mystery, Thriller','2019-06-24','Ari Aster', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (5,'2022-01-17','The French Dispatch','https://www.imdb.com/title/tt8847712/','movie',7.2,107,2021,'Comedy, Drama, Romance','2021-07-12','Wes Anderson', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (9,'2022-01-19','Knives Out','https://www.imdb.com/title/tt8946378/','movie',7.9,130,2019,'Comedy, Crime, Drama, Mystery, Thriller','2019-09-07','Rian Johnson', 'Daniel Craig, Chris Evans, Ana de Armas');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-08-29','Dark Waters','https://www.imdb.com/title/tt9071322/','movie',7.6,126,2019,'Biography, Drama, History','2019-11-12','Todd Haynes', 'Mark Ruffalo, Anne Hathaway, Tim Robbins');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2022-02-26','Der Name der Rose','https://www.imdb.com/title/tt0091605/','movie',7.7,130,1986,'Drama, History, Mystery, Thriller','1986-09-24','Jean-Jacques Annaud', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (10,'2021-08-13','Game of Thrones','https://www.imdb.com/title/tt0944947/','tvSeries',9.3,57,2011,'Action, Adventure, Drama, Fantasy','2011-04-16','', 'Emilia Clarke, Peter Dinklage, Kit Harington');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2021-11-01','Rain Man','https://www.imdb.com/title/tt0095953/','movie',8,133,1988,'Drama','1988-12-12','Barry Levinson', 'Dustin Hoffman, Tom Cruise, Valeria Golino');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (6,'2022-01-17','Last Night in Soho','https://www.imdb.com/title/tt9639470/','movie',7.1,116,2021,'Drama, Horror, Mystery, Thriller','2021-09-04','Edgar Wright', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2021-12-29','Dead Poets Society','https://www.imdb.com/title/tt0097165/','movie',8.1,128,1989,'Comedy, Drama','1989-06-02','Peter Weir', 'Robin Williams, Ethan Hawke');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (7,'2022-02-12','The Wolf of Wall Street','https://www.imdb.com/title/tt0993846/','movie',8.2,180,2013,'Biography, Comedy, Crime, Drama','2013-12-09','Martin Scorsese', '');
INSERT INTO Movie([YourRating],[DateRated],[Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast]) VALUES (8,'2022-01-31','Goodfellas','https://www.imdb.com/title/tt0099685/','movie',8.7,146,1990,'Biography, Crime, Drama','1990-09-09','Martin Scorsese', 'Robert De Niro, Ray Liotta, Joe Pesci');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Into the Wild','https://www.imdb.com/title/tt0758758/','movie',8.1,148,2007,'Adventure, Biography, Drama','2007-09-01','Sean Penn', '','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('The Father','https://www.imdb.com/title/tt10272386/','movie',8.3,97,2020,'Drama, Mystery','2020-01-27','Florian Zeller','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Retfærdighedens ryttere','https://www.imdb.com/title/tt11655202/','movie',7.6,116,2020,'Action, Comedy, Drama','2020-11-19','Anders Thomas Jensen','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Divas','https://www.imdb.com/title/tt15123120/','movie',7.7,80,2021,'Documentary','2021-08-18','Máté Körösi','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Ordinary People','https://www.imdb.com/title/tt0081283/','movie',7.8,124,1980,'Drama','1980-09-19','Robert Redford','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Gandhi','https://www.imdb.com/title/tt0083987/','movie',8.1,191,1982,'Biography, Drama','1982-11-30','Richard Attenborough','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Amadeus','https://www.imdb.com/title/tt0086879/','movie',8.4,160,1984,'Biography, Drama, Music','1984-09-06','Milos Forman','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Jakob the Liar','https://www.imdb.com/title/tt0120716/','movie',6.5,120,1999,'Drama, War','1999-09-16','Peter Kassovitz','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Valahol Európában','https://www.imdb.com/title/tt0039949/','movie',7.7,100,1947,'Drama','1947-12-23','Géza von Radványi','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Seven Years in Tibet','https://www.imdb.com/title/tt0120102/','movie',7.1,136,1997,'Adventure, Biography, Drama, History, War','1997-09-13','Jean-Jacques Annaud','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('No Country for Old Men','https://www.imdb.com/title/tt0477348/','movie',8.2,122,2007,'Crime, Drama, Thriller','2007-05-19','Ethan Coen, Joel Coen','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Scarface','https://www.imdb.com/title/tt0086250/','movie',8.3,170,1983,'Crime, Drama','1983-12-01','Brian De Palma','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('The Girl with the Dragon Tattoo','https://www.imdb.com/title/tt1568346/','movie',7.8,158,2011,'Crime, Drama, Mystery, Thriller','2011-12-12','David Fincher','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Wild','https://www.imdb.com/title/tt2305051/','movie',7.1,115,2014,'Adventure, Biography, Drama','2014-08-29','Jean-Marc Vallée','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Palmer','https://www.imdb.com/title/tt6857376/','movie',7.2,110,2021,'Drama','2021-01-29','Fisher Stevens','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Wrath of Man','https://www.imdb.com/title/tt11083552/','movie',7.1,119,2021,'Action, Crime, Thriller','2021-04-22','Guy Ritchie','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Minari','https://www.imdb.com/title/tt10633456/','movie',7.5,115,2020,'Drama','2020-01-26','Lee Isaac Chung','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('CODA','https://www.imdb.com/title/tt10366460/','movie',8.1,111,2021,'Comedy, Drama, Music','2021-01-29','Sian Heder','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Spencer','https://www.imdb.com/title/tt12536294/','movie',6.7,117,2021,'Biography, Drama','2021-09-03','Pablo Larraín','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('The Wire','https://www.imdb.com/title/tt0306414/','tvSeries',9.3,59,2002,'Crime, Drama, Thriller','2002-06-02','','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Peaky Blinders','https://www.imdb.com/title/tt2442560/','tvSeries',8.8,60,2013,'Crime, Drama','2013-09-12','','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Mephisto','https://www.imdb.com/title/tt0082736/','movie',7.7,144,1981,'Drama','1981-02-11','István Szabó','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Blade Runner 2049','https://www.imdb.com/title/tt1856101/','movie',8,164,2017,'Action, Drama, Mystery, Sci-Fi, Thriller','2017-10-03','Denis Villeneuve','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('The Lighthouse','https://www.imdb.com/title/tt7984734/','movie',7.4,109,2019,'Drama, Fantasy, Horror, Mystery','2019-05-19','Robert Eggers','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('La montaña sagrada','https://www.imdb.com/title/tt0071615/','movie',7.8,114,1973,'Adventure, Drama, Fantasy','1973-05-31','Alejandro Jodorowsky','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('V síti','https://www.imdb.com/title/tt11900404/','movie',8,100,2020,'Documentary, Crime','2020-02-27','Barbora Chalupová, Vít Klusák','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('El laberinto del fauno','https://www.imdb.com/title/tt0457430/','movie',8.2,118,2006,'Drama, Fantasy, War','2006-05-27','Guillermo del Toro','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Le fabuleux destin d''Amélie Poulain','https://www.imdb.com/title/tt0211915/','movie',8.3,122,2001,'Comedy, Romance','2001-04-25','Jean-Pierre Jeunet','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Madeo','https://www.imdb.com/title/tt1216496/','movie',7.8,129,2009,'Crime, Drama, Mystery, Thriller','2009-05-16','Bong Joon Ho','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('I''m Thinking of Ending Things','https://www.imdb.com/title/tt7939766/','movie',6.6,134,2020,'Drama, Thriller','2020-08-28','Charlie Kaufman','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Requiem for a Dream','https://www.imdb.com/title/tt0180093/','movie',8.3,102,2000,'Drama','2000-05-14','Darren Aronofsky','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Wild Roots','https://www.imdb.com/title/tt12719846/','movie',7.6,98,2021,'Drama','2021-08-26','Hajni Kis','','','');
INSERT INTO Movie([Title],[URL],[TitleType],[IMDbRating],[Runtimemins],[Year],[Genres],[ReleaseDate],[Directors], [Cast],[YourRating],[DateRated]) VALUES ('Kill Bill: Vol. 2','https://www.imdb.com/title/tt0378194/','movie',8,137,2004,'Action, Crime, Thriller','2004-04-08','Quentin Tarantino', '', '', '');
